language: c

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
  include:
    - os: osx
      osx_image: xcode7.3
      compiler: clang
    - os: linux
      compiler: gcc
      env: PYTHON_VERSION = "2.7"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - liblapack-dev
      - valgrind
      - gcc-4.8
      - g++-4.8
      - clang
      - cmake
      - cmake-data

install:
    - if [[ "$CC" == "gcc" ]]; then export CXX="g++-4.8"; fi

    - echo "$PYTHON_VERSION"
    - if [[ "$PYTHON_VERSION" == "2.7" ]]; then
         export TRAVIS_PYTHON_VERSION="2.7"
      fi

    # We do this conditionally because it saves us some downloading if the version is the same.
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
          wget https://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -O miniconda.sh;
        else
          wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
        fi
      else
        if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
        else
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        fi
      fi

    - bash miniconda.sh -b -p $HOME/miniconda
    - export CONDA_HOME="$HOME/miniconda"
    - export PATH="$CONDA_HOME/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a

    - travis/install_python_packages.py
      

env:
  global:
     - ERT_SHOW_BACKTRACE=1


script:
  - travis/build_total.py ert
