controls:
  -
    name: point
    type: generic_control
    min: -1
    max: 1
    initial_guess: 0.2
    perturbation_magnitude : 0.001
    auto_scale: True
    scaled_range: [0.3, 0.7]
    variables:
        - name: x
        - name: y
        - name: z


objective_functions:
  -
    name: distance


optimization:
  algorithm: optpp_q_newton
  convergence_tolerance: 0.001
  max_batch_num: 10

install_jobs:
  -
    name: distance3
    source: jobs/DISTANCE3

model:
  realizations: [0]

forward_model:
  - distance3 --point-file point.json
              --target 0.5 0.5 0.5
              --out distance
              --scaling -1 1 0.3 0.7

environment:
  simulation_folder: sim_output
  log_level: debug
  random_seed: 999

input_constraints:
  -
    weights: {point.x: 1.0, point.y: 1.0}
    upper_bound: 0.5
