controls:
  -
    name: point
    type: generic_control
    min: -1.0
    max: 1.0
    scaled_range: [-1, 1]
    initial_guess: 0
    perturbation_magnitude : 0.01
    variables:
        - name: x
        - name: y
        - name: z


objective_functions:
  - name: distance_p
    weight: 0.50
    scale: 0.6666666667
  - name: distance_q
    weight: 0.25


optimization:
  algorithm: optpp_q_newton
  convergence_tolerance: 0.005
  perturbation_num: 5
  max_batch_num: 3

install_jobs:
  -
    name: distance3
    executable: jobs/distance3.py

model:
  realizations: [0]

forward_model:
  - distance3 --point-file point.json
              --target 0.5 0.5 0.5
              --out distance_p
  - distance3 --point-file point.json
              --target -1.5 -1.5 0.5
              --out distance_q

simulator:
  queue_system:
    name: local

environment:
  simulation_folder: sim_output
  output_folder: everest_output_multiobj
  log_level: debug
  random_seed: 999
