name: Lint GitHub Actions workflows
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  actionlint:
    runs-on: ubuntu-latest
    name: Check all workflow files
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
      - name: Download shellcheck
        id: get_shellcheck
        run: |
          sudo apt-get update
          sudo apt-get install shellcheck
        shell: bash
      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
        shell: bash
      - name: Check testkomodo.sh
        run: shellcheck -s bash ci/testkomodo.sh
        shell: bash
